### PR TITLE
hooks moved to /hooks dir

### PR DESCRIPTION
**Pull request by marcinant**
IMHO there is a better and more elegant way to install hooks.

I think that you could consider a small refactoring on your project and move hooks to /hooks dir.
Then your hooks could be installed with `git init --template=<template_directory>` where `<template_directory>` is folder with this project repo cloned from github.

In this way there is no need to delete or symlink hooks folder (this is safe for other hooks in existing project). `git init` is safe for existing repositories.

### CODE REVIEW

**Comment by jaspernbrouwer** [comment]
I'm not going to merge this:

- Moving all hooks to a sub-directory is an unnecessary BC break, anyone pulling this change will need to change the symlinked/configured hooks directoy. Although I agree that a dedicated sub-directory is a bit cleaner, it isn't worth the BC break IMHO.

- There's some logic introduced in https://github.com/marcinant/git-flow-hooks/commit/98a6dffe7d5912d070de1ac8fe9bbf338bd4a225, which seams to initialize git-flow when it hasn't been initialized yet. This would enforce the usage of git-flow, which I do not agree with. That choice belongs to the user.

- I do agree that the installation procedure an be simplified. I think we can go even simpler: The latest version of git-flow (avh) will ask for a hooks and filters directory. If git-flow is already initialized, you can still configure the path: `git config gitflow.path.hooks /path/to/git-flow-hooks`.

**Comment by marcinant** [comment]
Ok. So, I'm going to merge these features to master on my fork and maintain this as separate project.

However few comments:

1. Personally I don't care about existing users. If they followed your `readme` and performed primitive procedure to install hooks then it's their and your choice.

I'm going to use this project with hooks in separate directory. Then I can configure git:
`git config --global init.templatedir '~/git-flow-hooks`

Every time I clone repository all hooks I need are installed automatically and `gitflow` is initialized. No need to symlink etc. The same applies for installation on existing repo. I described this earlier. (`git init --template=~/git-flow-hooks`)

2. With logic introduced in marcinant@98a6dff I can create and initialize an empty repository which is automatically prepared to work with gitflow.

I also don't agree with this opinion: "This would enforce the usage of git-flow, which I do not agree with. That choice belongs to the user."

User who symlinks your hooks or use my fork as git template is going to use gitflow.
This is the moment when user performed his choice.

If user still needs your hooks but doesn't want to initialize `gitflow` automatically, then simple solution is to delete `post-checkout` hook.

**Comment by jaspernbrouwer** [comment]
> Personally I don't care about existing users.

I initially created this project for the pure benefit of me and colleagues that work at the same company as I do. Now that it became somewhat popular, my aim is to be flexible and try to provide something that is usable for a wide range of cases/people.

> User who symlinks your hooks or use my fork as git template is going to use gitflow. This is the moment when user performed his choice.

I meant this choice on a repo basis. I personally don't use git-flow for _every_ repo. Some are too small and only maintained by me, so I don't need it there. Git-flow was thought up as a solution for a certain problem. When I don't have that problem, I don't need the solution.

> Ok. So, I'm going to merge these features to master on my fork and maintain this as separate project.

Please do! If you are going to use git-flow for every repo, I can imagine the setup can become bothersome.

I didn't mention it explicitly, but I've updated the readme with a simpler installation/activation procedure.

Also note that all the git-flow configuration options can be set at a global level.

**Comment by marcinant** [comment]
I understand. If you have strong user base then you need to take care of them.

However I think that my fork is just better and this is why I'm going to use it on my daily basis :)
I just prefer `git` template option instead of symlinking.

If I want to use `gitflow` on project then I clone repo with `--template=./.config/git/git-flow-hooks`.
If I don't want to use `gitflow` then I just simple clone without template or with another template dir.
It's simple and elegant. No symlinks (which can be broken). No need to initialize `gitflow` manually on each clone.

**Comment by dhilgarth** [comment]
@marcinant There is another way for every project to use these hooks. Simply execute 

```
git config --global --add gitflow.path.hooks d:\Path\to\git-flow-hooks\
```

**Pull request closed without merging**
